#pragma once
#define CONFIG_JSVM_MEM_LIMIT_KB 4096
#define CONFIG_JSVM_TASK_STACK_KB 256
#define CONFIG_JSVM_TASK_STACK_IN_PSRAM 0
#define CONFIG_JSVM_TASK_PRIORITY 5
#define CONFIG_JSVM_TASK_CORE 1
#define CONFIG_JSVM_QUEUE_DEPTH 8
#define CONFIG_JSVM_EXECUTION_TIMEOUT_MS 50
#define CONFIG_SPIRAM 0
