import type { KittyCharacter } from './characters';

export interface KittyPattern {
    rows: readonly string[];
    eyes: readonly { x: number; y: number; width: number; height: number }[];
}

// 每字符对应一格，. 为透明。女巫 46×47 / 1092 格、小鱼 30×23 / 450 格、围巾 21×22 / 284 格，
// 逐格来自用户网格图；经典款按最新宽脸参考图以半格精度还原。H01/H02 共用屏幕白色。
export const KITTY_PALETTE: Readonly<Record<string, number>> = {
    '#': 0x000000,
    'w': 0xffffff,
    'n': 0x35184f,
    'l': 0xeddcf8,
    'p': 0xf9c8cc,
    'r': 0xe36378,
    'o': 0xffb24f,
    'y': 0xffca6a,
    't': 0xcf7b43,
    'g': 0xefb545,
    'T': 0xb2714a,
    'R': 0xa74328,
    's': 0x2f2b2d,
    'b': 0x7fc1f8,
    'B': 0x1d6fad,
    'c': 0xd90027,
    'N': 0xffce45,
    'P': 0xfabead,
    'f': 0x941b39,
    'a': 0xf8a9ae,
    'e': 0xffd5d8,
    'C': 0xe22a21,
};

export const KITTY_PATTERNS: Readonly<Record<KittyCharacter, KittyPattern>> = {
    'kitty-classic': {
        rows: [
            '......................#####...............',
            '......................#####...............',
            '......#####..........##CCC##..######......',
            '......#####..........##CCC##..######......',
            '....##wwww###########CCCCCCC##wwww##......',
            '....##wwww###########CCCCCCC##wwww##......',
            '....##wwwwwwwwwwwww##CCCC###CC##ww####....',
            '....##wwwwwwwwwwwww##CCCC###CC##ww####....',
            '....##wwwwwwwwwwwww##CCCC#CCCCCC##CCCC##..',
            '....##wwwwwwwwwwwww##CCCC#CCCCCC##CCCC##..',
            '....##wwwwwwwwwwwwwww#####CCCCCC##CCCC##..',
            '....##wwwwwwwwwwwwwww#####CCCCCC##CCCC##..',
            '....##wwwwwwwwwwwwwwwwwwww######CCCCCC##..',
            '....##wwwwwwwwwwwwwwwwwwww######CCCCCC##..',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwww##CCCC##....',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwww##CCCC##....',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwwwww####......',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwwwww####......',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww##....',
            '..##wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww##....',
            '######wwww###wwwwwwwwwwwwww###wwww########',
            '######wwww###wwwwwwwwwwwwww###wwww########',
            '..##wwwwww###wwwwwwwwwwwwww###wwwwww##....',
            '..##wwwwww###wwwwwwwwwwwwww###wwwwww##....',
            '######PPPPwwwwwwwwwNNNNwwwwwwwPPPPPP######',
            '######PPPPwwwwwwwwwNNNNwwwwwwwPPPPPP######',
            '....##PPPPwwwwwwwwwwwwwwwwwwwwPPPPPP##....',
            '....##PPPPwwwwwwwwwwwwwwwwwwwwPPPPPP##....',
            '....####wwwwwwwwwwwwwwwwwwwwwwwwww####....',
            '....####wwwwwwwwwwwwwwwwwwwwwwwwww####....',
            '..##....##wwwwwwwwwwwwwwwwwwwwww##....##..',
            '..##....##wwwwwwwwwwwwwwwwwwwwww##....##..',
            '..........######################..........',
            '..........######################..........',
        ],
        eyes: [{ x: 10, y: 20, width: 3, height: 4 }, { x: 27, y: 20, width: 3, height: 4 }],
    },
    'kitty-witch': {
        rows: [
            '..............###.............................',
            '.............#nnn##...........................',
            '............#nnnnnn##.........................',
            '...........#nnn#nnnnn##.......................',
            '..........#nnn##nnnnnoo#......................',
            '........#.#n#####nnnnnoo#.....................',
            '........####...##nnnnnonn#....................',
            '.......#o##....##onnnnnnnn#...................',
            '.....##ooo##...#ooonnnn###n##.................',
            '......#o#o#.....#onnn##ooo#rr#...######.......',
            '.......#.#......##n###onnnorr####nnnnn##......',
            '......#...#.....###rrronnno###nnn#######......',
            '...............###rrrr#oooonnn####lw####......',
            '..............#lww#rr###nnnn##rr#lww###.......',
            '..............#lwww##nnnnn##rr#r#www##........',
            '..............#lnnnnnnnn###rr#r#######........',
            '...........###nnnnnnn###ll#rrr#rrr##rr#.......',
            '........###nnnnnnn###lllww#rrr#rrr#r#r#.......',
            '.......#nnnnnnn###lllwwwwww###l###r#rr#.......',
            '.......########lllwwwwwwwwwwwwwwl#rrr#........',
            '........#######lwwwwwwwwwwwwwwwwww####........',
            '.............#lwwwwwwwwwwwwwwwwwwwwll#........',
            '.............#lwwwwwwwwwwwwwwwwwwwww####......',
            '............####wwww##wwwwwwwwww##www#........',
            '...........#.#lwwwww##wwwwwwwwww##ww###.......',
            '.............###wwww##wwwwyywwww##www#.#......',
            '............#.#lwwpppwwwwwwwwwwwwppp##........',
            '..............###wpppwwwwwwwwwwwwppp#.#.......',
            '.............#..#wwwwwwwwwwwwwwwww##..........',
            '........####....##################........###.',
            '......##nnnn####nnnnnnnnnnnn#nn#####....##ttt#',
            '.....#nnnnnnnnnn############o##lwwww####ttttt#',
            '......##nnnn#######n#nnn######sll#ww#ttttt###.',
            '........#n#########n#nn#wwwww####t##tt####....',
            '........##########nnn##llwwwww#ttttt##........',
            '...........####w#nnnnnn#lllww#######..........',
            '....######..#####nnnnnnn#nnnn#ll#.............',
            '.###gggggg##w##w###nnnn##lww#lll#.............',
            '#gggggTTTggg#gg#tRR####llwww#ll##.............',
            '#TTTTggggTTT#gg#tR###llwwww#lll#..............',
            '#ggggTTTgggg#ttt##..#wwwww#####...............',
            '#TTTggggTTgtt###.....#wwww#...................',
            '#gggTggTgttt#.........####....................',
            '#ggggggttt##..................................',
            '.#Tggttt##....................................',
            '..#Ttt##......................................',
            '...###........................................',
        ],
        eyes: [{ x: 20, y: 23, width: 2, height: 3 }, { x: 32, y: 23, width: 2, height: 3 }],
    },
    'kitty-fish': {
        rows: [
            '..............................',
            '..........########............',
            '........##bbbbbbbb##..........',
            '......##bbbbbbbbbbbb##........',
            '.....#bbbbbbbbbb##bbbb#...##..',
            '....#bbb##bbbbb#cc####b#.#bb#.',
            '...#bbb#ww#####ccc#www#b#bbb#.',
            '..#bbbb#wwwwww#ccc##w##bbbbb#.',
            '..#bbbb#wwwwww#cc#cc#cc#bbBB#.',
            '.#bb#bb##wwwwww###cc#cc#bBb#..',
            '.#bbbbb#wwwwwwwwww##cc#bbbb#..',
            '..#bbb#wwwwwwwwwwwww###bbB#...',
            '..#bbb#wwwwwwwwwwwwwww#bbb#...',
            '.#bbb###ww#wwwwwww#ww###bBb#..',
            '.#Bbbb#sww#wwwwwww#wws#bbbB#..',
            '..#Bb###wwwwwwNwwwwww###Bbbb#.',
            '...#Bbb##wwwwwwwwwww##bB#Bbb#.',
            '....#B#b##wwwwwwwww##b##.#BB#.',
            '.....#BBbb#########bB##...##..',
            '......##BBbbbbbbbbBB#.........',
            '........##BBBBBBBB##..........',
            '..........########............',
            '..............................',
        ],
        eyes: [{ x: 10, y: 13, width: 1, height: 2 }, { x: 18, y: 13, width: 1, height: 2 }],
    },
    'kitty-scarf': {
        rows: [
            '.....................',
            '....###....ff........',
            '...#www###frrff.ff...',
            '...#wwwwwwfrffrfrrf..',
            '...#wwwwwwfrrfrffrf..',
            '...#wwwwwwwffwffrrf..',
            '..#wwwwwwwwwwwwwff#..',
            '..#wwwwwwwwwwwwwww#..',
            '..#wwwwwwwwwwwwwww#..',
            '.###ww#wwwwwww#ww###.',
            '..#www#wwwNwww#www#..',
            '..#wweewwwwwwweeww#..',
            '...#wwwwwwwwwwwww#...',
            '....fffffwwwfffff....',
            '...faaaaafffaaaaaf...',
            '...faaaaaaaaaaaaaf...',
            '....fffffffffffaf....',
            '....#wwwwwfaaaaf.....',
            '....#wwwww#faaaf.....',
            '.....#wwww#faaaf.....',
            '......####..fff......',
            '.....................',
        ],
        eyes: [{ x: 6, y: 9, width: 1, height: 2 }, { x: 14, y: 9, width: 1, height: 2 }],
    },
};
