#!/usr/bin/env python3
"""离线准备 NuttX 字体、共享 pxfont 解析器及分发许可；不修改源资源。"""
from __future__ import annotations

import argparse
from pathlib import Path
import struct


def write_if_changed(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)


def validate_font(data: bytes, name: str) -> None:
    """构建时检查每个字形的偏移和排序，让运行时可直接零拷贝访问。"""
    if len(data) < 16 or data[:5] != b"PXFN\x01":
        raise ValueError(f"{name}: 无效 pxfont 文件头")
    height, baseline = data[5:7]
    count, pool_size = struct.unpack_from("<II", data, 8)
    if not height or baseline > height or not count:
        raise ValueError(f"{name}: 无效字体尺寸/字形数量")
    if 16 + count * 8 + pool_size != len(data):
        raise ValueError(f"{name}: 字形表或位图池长度不匹配")
    previous = -1
    for index in range(count):
        cp, width, advance, offset = struct.unpack_from("<HBBI", data, 16 + index * 8)
        if cp <= previous or not advance or offset + ((width + 7) // 8) * height > pool_size:
            raise ValueError(f"{name}: 字形 {index} 排序/步进/位图范围无效")
        previous = cp


def first_file(candidates: list[Path], description: str) -> Path:
    for path in candidates:
        if path.is_file():
            return path
    raise FileNotFoundError(f"缺少{description}: " + ", ".join(str(path) for path in candidates))


def prepare(project: Path, repo_root: Path, output: Path) -> None:
    # 导出快照使用 shared/hal_display；在完整仓库中直接复用唯一字体源。
    cached = project / "shared/hal_display"
    source = cached if cached.is_dir() else repo_root / "firmware/components/hal_display"
    resources = {name: (source / f"fonts/{name}.pxf").read_bytes()
                 for name in ("pixel8", "pixel12", "pixel16")}
    for name, data in resources.items():
        validate_font(data, name)
    parser_source = (source / "src/pxfont.c").read_bytes()
    parser_header = (source / "include/hal_display/pxfont.h").read_bytes()
    licenses = {
        "pixelbox-pxfont-LICENSE": first_file(
            [source / "LICENSE", project / "LICENSE", repo_root / "LICENSE"], "pxfont 许可"),
        "fusion-pixel-OFL.txt": first_file(
            [source / "fonts/OFL.txt",
             repo_root / "simulator/src/renderer/src/device-sim/sandbox/fonts/OFL.txt"], "字体 OFL 许可"),
        "FONT-SOURCES.md": first_file(
            [source / "FONT-SOURCES.md", repo_root / "tools/fontgen/README.md"], "字体来源说明"),
    }
    # 数组至少四字节对齐，与 pxfont_load 的零拷贝结构体视图要求一致。
    lines = ["/* Generated by prepare_text.py; do not edit. */",
             "#ifndef PIXELBOX_GENERATED_FONTS_H", "#define PIXELBOX_GENERATED_FONTS_H"]
    for name, data in resources.items():
        lines.append(f"_Alignas(4) static const unsigned char px_font_{name}[] = {{")
        lines.extend(",".join(f"0x{byte:02x}" for byte in data[index:index + 32]) + ","
                     for index in range(0, len(data), 32))
        lines.append("};")
    lines.append("#endif\n")
    write_if_changed(output / "pixelbox_fonts.h", "\n".join(lines).encode())
    write_if_changed(output / "pxfont.c", parser_source)
    write_if_changed(output / "hal_display/pxfont.h", parser_header)
    for name, path in licenses.items():
        write_if_changed(output / "licenses" / name, path.read_bytes())


def main() -> None:
    project = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=project.parent)
    parser.add_argument("--output", type=Path, default=project / "generated")
    args = parser.parse_args()
    prepare(project, args.repo_root.resolve(), args.output.resolve())
    print(f"pixel8/pixel12/pixel16、pxfont 与许可已准备: {args.output}")


if __name__ == "__main__":
    main()
